### PR TITLE
[BUGFIX] Move JavaScript, CSS and Images into Resources/Public/

### PR DESCRIPTION
**Pull request by oliverklee**
Also copy the extension icon to `Resources/Public/Icons/Extension.gif`.

This allows accessing the static resources if the package
` helhum/typo3-secure-web` is used (where only public resources are available).

This will help with #106.

### CODE REVIEW

**Comment by oliverklee** [comment]
Note: I have not tested this manually yet.

**Comment by oliverklee** [comment]
The build failure does not seem to be related to this change.

**Comment by oliverklee** [comment]
Thanks for the merge!

**Comment by rengaw83** [comment]
no problem, the ci tasks are fixed too and not related to the pr's.

**Comment by rengaw83** [comment]
But now i have problems with seminars and ontimeaccount extension. There are som typoscript including some mkforms js files.
should i create issues or you have allready fixed that?

**Comment by oliverklee** [comment]
Please create an issue (one for each extension). I'll take care of that. I'll need a new release of mkforms for this, though.

**Comment by rengaw83** [comment]
For seminars you allready hava a issue: https://github.com/oliverklee/ext-seminars/issues/465
For onetimeaccount i have created a new pr: https://github.com/oliverklee/ext-onetimeaccount/pull/135
A new  release of mkforms was created too.
Thanks!

**Comment by oliverklee** [comment]
Thanks!

I've looked at this a bit more: Maybe we can reduce the fallout by providing the files in the old locations as well, mark those as deprecated and to be removed (as a breaking change) in the next major release (using the semantic versioning schema). What do you think?

**Comment by rengaw83** [comment]
Breaking changes are always a difficult thing.

I am not a friend of having duplicate files in git.  
When we have to do fixes on one file, we has to the changes on all duplicate files. 
hardly anyone will think of that.
Symlinking the files can be an option, but this will not work on some machines like windows.

mkforms is backward compatible to TYPO3 7.6. I think it is not a problem to fix the paths in seminars and onetimeaccount and change the dependencies to `mkforms:^9.5.2`. 

In this case, is that okay with you?

**Comment by oliverklee** [comment]
I have created a PR so mkforms does not break old seminars and onetimeaccount installations. Maybe I can add a note to the files stating that these will not get any bug fixes?

**Pull request merged**
