### PR TITLE
[CLEANUP] Remove unused private fields and methods

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
Do you need anything from me so you can merge this PR?

**Comment by oliverklee** [comment]
Rebased.

**Comment by oliverklee** [comment]
ping

**Comment by oliverklee** [comment]
ping

**Comment by hannesbochmann** [comment]
I can't merge this pull request in the moment as the methods (replaceValue, replaceRdt) that have been removed in tx_mkforms_util_FormBaseAjax are in use in evalSecureExpression(). 
The same goes for the methods processPerimetersCallBackClearNotUsed and processPerimetersCallBackKeepNotUsed in tx_mkforms_util_Templates. The rest is fine.

I guess you're using a tool to clean up the code and rely on the tool to work correct, right? If so, please be more careful and double check the taken changes.

**Comment by oliverklee** [comment]
done

**Pull request merged**
