### PR TITLE
[BUGFIX] Make toWebPath play nicely with absRefPrefix

### PR DESCRIPTION
**Pull request by oliverklee**
Div::toWebPath wreaks havoc if a absRefPrefix is set.

This commit converts this method to a thin wrapper for
t3lib_div::locationHeaderUrl.

### CODE REVIEW

**Comment by hannesbochmann** [comment]
What happens exactly when absRefPrefix is set?

**Comment by oliverklee** [comment]
This is the scenario which I've tested locally:

1. The domain is "root.local"
2. The site is located in a subdirectory "subdir".
3. baseURL is not set, but config.absRefPrefix is set to "/subdir/" (as mentioned on https://buzz.typo3.org/people/soeren-malling/article/baseurl-is-dead-long-live-absrefprefix/ ).

Now the form action without the fix would contain the absRefPrefix two times:

http://root.local/subdir/subdir/index.php?id=13

With the fix, the form action correctly contains the absRefPrefix only once:

http://root.local/subdir/index.php?id=13

**Comment by oliverklee** [comment]
ping

**Comment by oliverklee** [comment]
@hannesbochmann Is there anything missing from the PR which I can provide to get it merged?

**Comment by hannesbochmann** [comment]
No, everything is fine. We just had no time to check it.

**Comment by oliverklee** [comment]
Rebased and re-pushed.

**Comment by oliverklee** [comment]
ping (after rebasing after every upstream change)

**Comment by oliverklee** [comment]
@hannesbochmann  Could you please review and merge this bugfix? Thanks!

**Comment by hannesbochmann** [comment]
Sorry, the created URLs are not the same as before which lead to errors. So we sadly can't accept this pull request.

**Comment by oliverklee** [comment]
Um, please don't just close the PR as the original bug then won't be fixed.

What exactly is the problematic behavior with this PR?

**Comment by hannesbochmann** [comment]
If I have a $path like profile/registration.html, no absRefPrefix is set and baseUrl is set. the resulting URL will only be the domain like root.local. Without the fix the URL would be root.local/profile/registration.html

**Pull request closed without merging**
