### PR TITLE
Move the codebase to PSR-2

### PR DESCRIPTION
**Pull request by Konafets**

### CODE REVIEW

**Comment by rengaw83** [comment]
PSR-2 says Code MUST use 4 spaces for indenting, not tabs.
We use tabs for indending curently.
I think this request will not be merged at the moment.

**Comment by Konafets** [comment]
What is the problem with spaces?

**Comment by oliverklee** [comment]
@digedag commented on the reasons here:
https://github.com/digedag/rn_base/issues/38#issuecomment-195772159

**Comment by oliverklee** [comment]
https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by Konafets** [comment]
I do use vim over emacs as well :-)

**Pull request closed without merging**
